version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: shortener_mongo
    env_file:
      - envs/.docker.env
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    command: --wiredTigerCacheSizeGB 1.5
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: shortener_mongo_express
    env_file:
      - envs/.docker.env
    ports:
      - 8081:8081
    restart: unless-stopped

volumes:
  mongo_data:
